### ISSUE TITLE
Implement get_if overloads (was: No compile error with invalid call to target)

### ISSUE THREAD

**Issue by jcelerier** [eggs-cpp/variant#27] opened 2017-03-29 10:45 UTC
Hello: 

The compiler happily accepts the following code:

```
#include <eggs/variant.hpp>
#include <string>
int main()
{
  eggs::variant<int, bool> foo;
  foo.target<std::string>();
}
```

couldn't it be made so that `target<T>` only compiles if the variant actually has a T type ?

**Comment by K-ballo** [comment] 2017-03-29 12:04
This is by design, as `variant::target` models a poor man's `dynamic_cast`:

    #include <string>
    struct variant { virtual ~variant(){} };
    int main()
    {
      variant foo;
      dynamic_cast<std::string*>(&foo); // no error
    }

It could certainly be changed, but what would the motivation be? What's the rationale for not using the value access functions instead? Would this use case be better served by a `get_if`, like the one the standard library has?

**Comment by jcelerier** [comment] 2017-03-29 12:11
>  Would this use case be better served by a get_if, like the one the standard library has?

Yes, I did not know about get_if but this is the behaviour I am looking for (https://godbolt.org/g/tjdW31).

**Comment by viboes** [comment] 2017-03-29 16:18
get_if template parameter must be one of the alternatives

http://en.cppreference.com/w/cpp/utility/variant/get_if

**Comment by K-ballo** [comment] 2017-03-31 16:38
I have just pushed the implementation of `get_if` overloads to the _develop_ branch. The current wording does not guarantee them to be ill-formed for invalid calls, but the implementation does require it; as a result, the compilation errors can be quite poor.

Adding ill-formed guarantees for `variant_element`, `get`, and `get_if` comes next. I will take this opportunity to go over the API and check that all SFINAE conditions are checked for, and all ill-formed conditions yield a decent, `static_assert`-based, error message.

**Comment by K-ballo** [comment] 2017-04-02 14:56
Ill-formed guarantees and decent error messages are now in the _develop_ branch. Will close this issue once they are merged to the _master_ branch.

**Closed** 2017-04-03 16:48 UTC

**Comment by jcelerier** [comment] 2017-04-03 18:55
thank you very much !
